# Blasphemous Requiem Aeternam theme for Bottom

[color]
background = "#000000"
foreground = "#ba8540"
border = "#ba8540"
text = "#ba8540"
selected_text = "#000000"
selected_bg = "#ba8540"

[colors]
cpu_color = "#ba8540"
mem_color = "#8a6030"
swap_color = "#5a4020"
rx_color = "#c8a060"
tx_color = "#ba8540"
rx_total_color = "#a07040"
tx_total_color = "#c8a060"
process_color = "#ba8540"
process_highlighted_color = "#d49e52"
average_cpu_color = "#c8a060"
